{{- if not .Values.api.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vesta.fullname" . }}-api-db
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "vesta.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.api.database.url | quote }}
{{- end }}
