package controllers

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	vestav1alpha1 "kubernetes.getvesta.sh/operator/api/v1alpha1"
)

// Fluent Bit routes by tag, and a record carries exactly one tag. Everything about how
// drains are scoped follows from that.
//
// Records are tagged "vesta.<namespace>.<app>" by a Lua filter, and each drain becomes an
// OUTPUT whose Match covers the tags it wants. A record reaches every OUTPUT whose pattern
// covers it, so inheritance -- an app shipping to the platform drain and its project's and
// its own -- needs no merging step at all.
const (
	drainTagPrefix   = "vesta"
	fluentBitVersion = "3.1.9"
)

// DrainTarget is a drain together with the namespaces its scope resolves to. The controller
// does the resolving, because it is the part that needs a cluster; rendering stays pure so
// the routing can be tested without one.
type DrainTarget struct {
	Drain vestav1alpha1.VestaLogDrain
	// Namespaces is empty for a platform-wide drain. Otherwise it is the concrete list,
	// resolved from project and environment rather than pattern-matched: project "shop"
	// and project "shop-extra" both prefix the namespace "shop-extra-prod", and a glob
	// cannot tell them apart.
	Namespaces []string
	// ExcludedApps holds "<namespace>/<app>" pairs that opted out of this drain by
	// declaring a disabled drain of the same name at a narrower scope.
	ExcludedApps []string
	// IncludedApps is every "<namespace>/<app>" in this drain's scope, needed only when
	// ExcludedApps is non-empty: Fluent Bit has no negative Match, so an opt-out is
	// expressed by enumerating what remains.
	IncludedApps []string
}

// RenderFluentBitConfig builds the whole collector configuration.
func RenderFluentBitConfig(targets []DrainTarget) (string, error) {
	var b strings.Builder

	b.WriteString(`# Generated by the Vesta operator. Do not edit: every change is overwritten
# on the next reconcile, and the DaemonSet is rolled when this file's checksum changes.

[SERVICE]
    Flush                     5
    Daemon                    Off
    Log_Level                 info
    Parsers_File              parsers.conf
    HTTP_Server               On
    HTTP_Listen               0.0.0.0
    HTTP_Port                 2020
    Health_Check              On
    storage.path              /flb-storage/
    storage.sync              normal
    storage.checksum          off
    storage.backlog.mem_limit 16M

[INPUT]
    Name                tail
    Tag                 kube.*
    Path                /var/log/containers/*.log
    # The node's container runtime decides the on-disk format; this parser handles both
    # docker and CRI, so the collector does not have to be told which runtime it is on.
    multiline.parser    docker, cri
    Mem_Buf_Limit       16MB
    Skip_Long_Lines     On
    Refresh_Interval    10
    storage.type        filesystem
    # Without this the collector re-ships every log on the node after a restart.
    DB                  /flb-storage/tail.db
    DB.locking          true

[FILTER]
    Name                kubernetes
    Match               kube.*
    Kube_Tag_Prefix     kube.var.log.containers.
    Merge_Log           On
    Keep_Log            Off
    K8S-Logging.Parser  On
    K8S-Logging.Exclude On
    Labels              On
    # Annotations carry no routing information and are frequently large.
    Annotations         Off

[FILTER]
    Name   lua
    Match  kube.*
    script vesta.lua
    call   set_route

[FILTER]
    Name                  rewrite_tag
    Match                 kube.*
    Rule                  $vesta_route ^(.+)$ ` + drainTagPrefix + `.$1 false
    Emitter_Name          vesta_drains
    Emitter_Storage.type  filesystem
`)

	if len(targets) == 0 {
		// A collector with no outputs still runs, tails, and reports healthy. Saying so
		// here is what stops "no logs arriving" from looking like a broken collector.
		b.WriteString(`
# No log drains are defined. Records are collected and discarded; define a VestaLogDrain
# to route them somewhere.
[OUTPUT]
    Name  null
    Match *
`)
		return b.String(), nil
	}

	sorted := append([]DrainTarget(nil), targets...)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Drain.Name < sorted[j].Drain.Name
	})

	for _, target := range sorted {
		section, err := renderOutput(target)
		if err != nil {
			return "", fmt.Errorf("drain %s: %w", target.Drain.Name, err)
		}
		b.WriteString("\n")
		b.WriteString(section)
	}

	return b.String(), nil
}

// RenderRouteScript is the Lua that derives a record's route from its Kubernetes metadata.
//
// It is Lua rather than the `modify` filter because the route joins two fields, and modify
// can only copy or set constants. rewrite_tag then turns the field into a tag with a plain
// capture group, avoiding any assumption about record accessors being expanded inside a
// new tag.
func RenderRouteScript() string {
	return `-- Generated by the Vesta operator. Do not edit.
--
-- Builds "<namespace>.<app>" for each record, which rewrite_tag turns into the record's
-- tag. Pods without a Vesta app label are dropped rather than routed: they are the
-- cluster's own components, including Vesta's API, whose logs can contain request detail
-- that has no business being shipped to an app's drain.
function set_route(tag, timestamp, record)
    local k = record["kubernetes"]
    if k == nil then
        return -1, timestamp, record
    end

    local labels = k["labels"]
    if labels == nil then
        return -1, timestamp, record
    end

    local app = labels["kubernetes.getvesta.sh/app"]
    if app == nil or app == "" then
        return -1, timestamp, record
    end

    local ns = k["namespace_name"]
    if ns == nil or ns == "" then
        return -1, timestamp, record
    end

    record["vesta_route"] = ns .. "." .. app
    record["vesta_app"] = app
    record["vesta_namespace"] = ns

    local project = labels["kubernetes.getvesta.sh/project"]
    if project ~= nil then
        record["vesta_project"] = project
    end

    -- 2 means the record was modified.
    return 2, timestamp, record
end
`
}

// matchFor turns a drain's resolved scope into the Match or Match_Regex line for its OUTPUT.
func matchFor(target DrainTarget) string {
	app := strings.TrimSpace(target.Drain.Spec.App)

	// The common case: everything, with nothing opting out.
	if len(target.Namespaces) == 0 && app == "" && len(target.ExcludedApps) == 0 {
		return fmt.Sprintf("    Match                 %s.*\n", drainTagPrefix)
	}

	// An opt-out cannot be expressed as an exclusion -- Fluent Bit has no negative Match,
	// and relying on a regex lookahead would make routing depend on which regex engine the
	// collector was built with. So exclusions turn the pattern inside out: enumerate what
	// is included instead. Only drains that actually have an opt-out pay for it.
	if len(target.ExcludedApps) > 0 {
		return matchRegexExcluding(target)
	}

	if len(target.Namespaces) == 1 && app != "" {
		return fmt.Sprintf("    Match                 %s.%s.%s\n", drainTagPrefix, target.Namespaces[0], app)
	}
	if len(target.Namespaces) == 1 {
		return fmt.Sprintf("    Match                 %s.%s.*\n", drainTagPrefix, target.Namespaces[0])
	}

	if len(target.Namespaces) == 0 && app != "" {
		return fmt.Sprintf("    Match_Regex           ^%s\\.[^.]+\\.%s$\n", drainTagPrefix, regexp.QuoteMeta(app))
	}

	quoted := make([]string, 0, len(target.Namespaces))
	for _, ns := range target.Namespaces {
		quoted = append(quoted, regexp.QuoteMeta(ns))
	}
	sort.Strings(quoted)

	suffix := ".*"
	if app != "" {
		suffix = regexp.QuoteMeta(app) + "$"
	}
	return fmt.Sprintf("    Match_Regex           ^%s\\.(%s)\\.%s\n",
		drainTagPrefix, strings.Join(quoted, "|"), suffix)
}

// matchRegexExcluding builds an inclusion list for a drain some apps have opted out of.
func matchRegexExcluding(target DrainTarget) string {
	excluded := make(map[string]bool, len(target.ExcludedApps))
	for _, pair := range target.ExcludedApps {
		excluded[pair] = true
	}

	included := make([]string, 0, len(target.IncludedApps))
	for _, pair := range target.IncludedApps {
		if excluded[pair] {
			continue
		}
		ns, app, found := strings.Cut(pair, "/")
		if !found {
			continue
		}
		included = append(included,
			fmt.Sprintf("%s\\.%s", regexp.QuoteMeta(ns), regexp.QuoteMeta(app)))
	}
	sort.Strings(included)

	if len(included) == 0 {
		// Every app in scope opted out. Match nothing rather than fall back to matching
		// everything, which is what an empty alternation would do.
		return fmt.Sprintf("    Match_Regex           ^%s\\.$^\n", drainTagPrefix)
	}

	return fmt.Sprintf("    Match_Regex           ^%s\\.(%s)$\n",
		drainTagPrefix, strings.Join(included, "|"))
}

// renderOutput writes the OUTPUT section for one drain.
func renderOutput(target DrainTarget) (string, error) {
	spec := target.Drain.Spec
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# %s (%s)\n", target.Drain.Name, describeScope(spec)))
	b.WriteString("[OUTPUT]\n")

	body, err := outputBody(target.Drain.Name, spec)
	if err != nil {
		return "", err
	}
	b.WriteString(body)
	b.WriteString(matchFor(target))

	if spec.Retry != nil {
		if spec.Retry.Limit != "" {
			b.WriteString(kv("Retry_Limit", spec.Retry.Limit))
		}
		if spec.Retry.StorageType != "" {
			b.WriteString(kv("storage.total_limit_size", "512M"))
		}
	}

	return b.String(), nil
}

func outputBody(name string, spec vestav1alpha1.VestaLogDrainSpec) (string, error) {
	switch spec.Type {
	case "http":
		if spec.HTTP == nil || spec.HTTP.URI == "" {
			return "", fmt.Errorf("type is http but no uri is set")
		}
		return renderHTTP(name, spec.HTTP), nil
	case "loki":
		if spec.Loki == nil || spec.Loki.Host == "" {
			return "", fmt.Errorf("type is loki but no host is set")
		}
		return renderLoki(name, spec.Loki), nil
	case "syslog":
		if spec.Syslog == nil || spec.Syslog.Host == "" {
			return "", fmt.Errorf("type is syslog but no host is set")
		}
		return renderSyslog(name, spec.Syslog), nil
	case "elasticsearch":
		if spec.Elasticsearch == nil || spec.Elasticsearch.Host == "" {
			return "", fmt.Errorf("type is elasticsearch but no host is set")
		}
		return renderElasticsearch(name, spec.Elasticsearch), nil
	case "datadog":
		if spec.Datadog == nil || spec.Datadog.APIKey == nil {
			return "", fmt.Errorf("type is datadog but no apiKey secret is referenced")
		}
		return renderDatadog(name, spec.Datadog), nil
	case "s3":
		if spec.S3 == nil || spec.S3.Bucket == "" {
			return "", fmt.Errorf("type is s3 but no bucket is set")
		}
		return renderS3(name, spec.S3), nil
	case "forward":
		if spec.Forward == nil || spec.Forward.Host == "" {
			return "", fmt.Errorf("type is forward but no host is set")
		}
		return renderForward(name, spec.Forward), nil
	case "openobserve":
		if spec.OpenObserve == nil || spec.OpenObserve.Endpoint == "" {
			return "", fmt.Errorf("type is openobserve but no endpoint is set")
		}
		return renderOpenObserve(name, spec.OpenObserve), nil
	}
	return "", fmt.Errorf("unknown drain type %q", spec.Type)
}

func renderHTTP(name string, d *vestav1alpha1.HTTPDrain) string {
	var b strings.Builder
	b.WriteString(kv("Name", "http"))
	b.WriteString(kv("Alias", name))

	uri, host, port, tls := splitEndpoint(d.URI)
	b.WriteString(kv("Host", host))
	b.WriteString(kv("Port", port))
	b.WriteString(kv("URI", uri))
	b.WriteString(kv("Format", orDefault(d.Format, "json")))
	if tls {
		b.WriteString(kv("tls", "On"))
		b.WriteString(kv("tls.verify", onOff(d.TLSVerify, true)))
	}
	if d.Compress != "" {
		b.WriteString(kv("compress", d.Compress))
	}
	for _, key := range sortedMapKeys(d.Headers) {
		b.WriteString(kv("Header", key+" "+d.Headers[key]))
	}
	if d.AuthHeader != nil {
		// ${...} is expanded by the collector from its environment, which is populated
		// from the mounted Secret. The credential never enters this file.
		b.WriteString(kv("Header", "Authorization ${"+secretEnvVar(name, "AUTH")+"}"))
	}
	b.WriteString(kv("json_date_key", orDefault(d.DateKey, "timestamp")))
	b.WriteString(kv("json_date_format", "iso8601"))
	return b.String()
}

func renderLoki(name string, d *vestav1alpha1.LokiDrain) string {
	var b strings.Builder
	b.WriteString(kv("Name", "loki"))
	b.WriteString(kv("Alias", name))
	b.WriteString(kv("Host", d.Host))
	b.WriteString(kv("Port", portOrDefault(d.Port, 3100)))

	// Vesta's own three always go on, so a drain is queryable by app without the operator
	// having had to think about labels.
	labels := []string{
		"project=$vesta_project", "namespace=$vesta_namespace", "app=$vesta_app",
	}
	for _, key := range sortedMapKeys(d.Labels) {
		labels = append(labels, key+"="+d.Labels[key])
	}
	b.WriteString(kv("labels", strings.Join(labels, ",")))

	if d.TenantID != "" {
		b.WriteString(kv("tenant_id", d.TenantID))
	}
	if d.BasicAuth != nil {
		b.WriteString(kv("http_user", "${"+secretEnvVar(name, "USER")+"}"))
		b.WriteString(kv("http_passwd", "${"+secretEnvVar(name, "PASSWORD")+"}"))
	}
	if boolOr(d.TLS, false) {
		b.WriteString(kv("tls", "On"))
		b.WriteString(kv("tls.verify", onOff(d.TLSVerify, true)))
	}
	b.WriteString(kv("line_format", "json"))
	return b.String()
}

func renderSyslog(name string, d *vestav1alpha1.SyslogDrain) string {
	var b strings.Builder
	b.WriteString(kv("Name", "syslog"))
	b.WriteString(kv("Alias", name))
	b.WriteString(kv("Host", d.Host))
	b.WriteString(kv("Port", portOrDefault(d.Port, 514)))
	b.WriteString(kv("Mode", orDefault(d.Mode, "tcp")))
	b.WriteString(kv("syslog_format", orDefault(d.Format, "rfc5424")))
	b.WriteString(kv("syslog_hostname_key", orDefault(d.HostnameKey, "vesta_namespace")))
	b.WriteString(kv("syslog_appname_key", orDefault(d.AppNameKey, "vesta_app")))
	b.WriteString(kv("syslog_message_key", orDefault(d.MessageKey, "log")))
	if d.SeverityKey != "" {
		b.WriteString(kv("syslog_severity_key", d.SeverityKey))
	}
	if d.FacilityKey != "" {
		b.WriteString(kv("syslog_facility_key", d.FacilityKey))
	}
	if d.MaxSizeBytes > 0 {
		b.WriteString(kv("syslog_maxsize", fmt.Sprint(d.MaxSizeBytes)))
	}
	if strings.EqualFold(d.Mode, "tls") {
		b.WriteString(kv("tls", "On"))
		b.WriteString(kv("tls.verify", onOff(d.TLSVerify, true)))
	}
	return b.String()
}

func renderElasticsearch(name string, d *vestav1alpha1.ElasticsearchDrain) string {
	var b strings.Builder
	b.WriteString(kv("Name", "es"))
	b.WriteString(kv("Alias", name))
	b.WriteString(kv("Host", d.Host))
	b.WriteString(kv("Port", portOrDefault(d.Port, 9200)))

	if boolOr(d.LogstashFormat, false) {
		b.WriteString(kv("Logstash_Format", "On"))
		b.WriteString(kv("Logstash_Prefix", orDefault(d.LogstashPrefix, "vesta")))
	} else {
		b.WriteString(kv("Index", orDefault(d.Index, "vesta")))
	}
	if d.Type != "" {
		b.WriteString(kv("Type", d.Type))
	}
	// Elasticsearch 8 removed mapping types and rejects a batch that carries one, so this
	// defaults on: the failure it prevents is a total delivery failure, not a degraded one.
	b.WriteString(kv("Suppress_Type_Name", onOff(d.SuppressTypeName, true)))

	if d.BasicAuth != nil {
		b.WriteString(kv("HTTP_User", "${"+secretEnvVar(name, "USER")+"}"))
		b.WriteString(kv("HTTP_Passwd", "${"+secretEnvVar(name, "PASSWORD")+"}"))
	}
	if d.CloudID != nil {
		b.WriteString(kv("Cloud_ID", "${"+secretEnvVar(name, "CLOUD_ID")+"}"))
	}
	if boolOr(d.TLS, false) {
		b.WriteString(kv("tls", "On"))
		b.WriteString(kv("tls.verify", onOff(d.TLSVerify, true)))
	}
	b.WriteString(kv("Replace_Dots", "On"))
	b.WriteString(kv("Trace_Error", "On"))
	return b.String()
}

func renderDatadog(name string, d *vestav1alpha1.DatadogDrain) string {
	var b strings.Builder
	b.WriteString(kv("Name", "datadog"))
	b.WriteString(kv("Alias", name))
	// The regional host matters: EU data posted to the US endpoint is accepted and lands
	// in the wrong account, with nothing reported as an error.
	b.WriteString(kv("Host", "http-intake.logs."+orDefault(d.Site, "datadoghq.com")))
	b.WriteString(kv("TLS", "on"))
	b.WriteString(kv("apikey", "${"+secretEnvVar(name, "API_KEY")+"}"))
	b.WriteString(kv("dd_service", orDefault(d.Service, "$vesta_app")))
	b.WriteString(kv("dd_source", orDefault(d.Source, "vesta")))

	tags := []string{"project:$vesta_project", "env:$vesta_namespace"}
	for _, key := range sortedMapKeys(d.Tags) {
		tags = append(tags, key+":"+d.Tags[key])
	}
	b.WriteString(kv("dd_tags", strings.Join(tags, ",")))
	if d.Compress != "" {
		b.WriteString(kv("compress", d.Compress))
	}
	if boolOr(d.IncludeTagKey, false) {
		b.WriteString(kv("include_tag_key", "true"))
	}
	return b.String()
}

func renderS3(name string, d *vestav1alpha1.S3Drain) string {
	var b strings.Builder
	b.WriteString(kv("Name", "s3"))
	b.WriteString(kv("Alias", name))
	b.WriteString(kv("bucket", d.Bucket))
	b.WriteString(kv("region", orDefault(d.Region, "us-east-1")))
	if d.Endpoint != "" {
		b.WriteString(kv("endpoint", d.Endpoint))
	}
	b.WriteString(kv("total_file_size", orDefault(d.TotalFileSize, "50M")))
	b.WriteString(kv("upload_timeout", orDefault(d.UploadTimeout, "10m")))
	b.WriteString(kv("s3_key_format", orDefault(d.S3KeyFormat,
		"/$TAG/%Y/%m/%d/%H_%M_%S_$UUID.gz")))
	b.WriteString(kv("compression", orDefault(d.Compression, "gzip")))
	if d.StorageClass != "" {
		b.WriteString(kv("storage_class", d.StorageClass))
	}
	if boolOr(d.UsePutObject, false) {
		b.WriteString(kv("use_put_object", "On"))
	}
	// Credentials are omitted entirely when absent, which is what lets IRSA or an instance
	// role supply them -- writing empty values here would override those with nothing.
	if d.Credentials != nil {
		b.WriteString(kv("aws_access_key_id", "${"+secretEnvVar(name, "AWS_ACCESS_KEY_ID")+"}"))
		b.WriteString(kv("aws_secret_access_key", "${"+secretEnvVar(name, "AWS_SECRET_ACCESS_KEY")+"}"))
	}
	return b.String()
}

// DrainEnvVar is the environment variable a drain's credential is mounted as. Derived from
// the drain name so two drains of the same type cannot collide.
//
// Exported because the controller uses it to build the collector's environment and the
// renderer uses it to reference that environment. If the two disagreed, every credential
// would expand to an empty string and every authenticated drain would fail to deliver.
func DrainEnvVar(drainName, suffix string) string {
	sanitised := nonAlphanumeric.ReplaceAllString(strings.ToUpper(drainName), "_")
	return "VESTA_DRAIN_" + sanitised + "_" + suffix
}

func secretEnvVar(drainName, suffix string) string { return DrainEnvVar(drainName, suffix) }

var nonAlphanumeric = regexp.MustCompile(`[^A-Z0-9]+`)

func describeScope(spec vestav1alpha1.VestaLogDrainSpec) string {
	projects := scopeProjects(spec)
	// Named rather than counted: "3 projects" in a status field is the start of a question
	// instead of the end of one.
	list := strings.Join(projects, ", ")

	switch {
	case spec.App != "" && spec.Environment != "":
		return fmt.Sprintf("app %s in %s/%s", spec.App, list, spec.Environment)
	case spec.App != "":
		return "app " + spec.App
	case spec.Environment != "" && len(projects) > 0:
		return fmt.Sprintf("projects %s, environment %s", list, spec.Environment)
	case spec.Environment != "":
		return "environment " + spec.Environment
	case len(projects) == 1:
		return "project " + list
	case len(projects) > 1:
		return "projects " + list
	}
	return "all apps"
}

func kv(key, value string) string {
	return fmt.Sprintf("    %-21s %s\n", key, value)
}

func orDefault(value, fallback string) string {
	if strings.TrimSpace(value) == "" {
		return fallback
	}
	return value
}

func portOrDefault(port int32, fallback int) string {
	if port > 0 {
		return fmt.Sprint(port)
	}
	return fmt.Sprint(fallback)
}

func boolOr(value *bool, fallback bool) bool {
	if value == nil {
		return fallback
	}
	return *value
}

func onOff(value *bool, fallback bool) string {
	if boolOr(value, fallback) {
		return "On"
	}
	return "Off"
}

func sortedMapKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// splitEndpoint breaks a URI into the host, port, path and TLS flag the http output needs
// as separate settings.
func splitEndpoint(uri string) (path, host, port string, tls bool) {
	trimmed := uri
	tls = strings.HasPrefix(trimmed, "https://")
	trimmed = strings.TrimPrefix(strings.TrimPrefix(trimmed, "https://"), "http://")

	hostPort := trimmed
	path = "/"
	if i := strings.Index(trimmed, "/"); i >= 0 {
		hostPort = trimmed[:i]
		path = trimmed[i:]
	}

	host = hostPort
	if h, p, found := strings.Cut(hostPort, ":"); found {
		host, port = h, p
	} else if tls {
		port = "443"
	} else {
		port = "80"
	}
	return path, host, port, tls
}

// renderOpenObserve emits the http output aimed at OpenObserve's JSON ingest API.
func renderOpenObserve(name string, d *vestav1alpha1.OpenObserveDrain) string {
	var b strings.Builder
	b.WriteString(kv("Name", "http"))
	b.WriteString(kv("Alias", name))

	_, host, port, tls := splitEndpoint(d.Endpoint)
	b.WriteString(kv("Host", host))
	b.WriteString(kv("Port", port))
	b.WriteString(kv("URI", fmt.Sprintf("/api/%s/%s/_json",
		orDefault(d.Organization, "default"), orDefault(d.Stream, "vesta"))))
	b.WriteString(kv("Format", "json"))

	if tls {
		b.WriteString(kv("tls", "On"))
		b.WriteString(kv("tls.verify", onOff(d.TLSVerify, true)))
	}
	if d.Credentials != nil {
		// http_user and http_passwd, not a hand-built Authorization header: the collector
		// does the base64 itself, so nobody has to paste a pre-encoded credential.
		b.WriteString(kv("http_user", "${"+secretEnvVar(name, "USER")+"}"))
		b.WriteString(kv("http_passwd", "${"+secretEnvVar(name, "PASSWORD")+"}"))
	}
	if d.Compress != "" {
		b.WriteString(kv("compress", d.Compress))
	}
	// OpenObserve orders on _timestamp; anything else leaves it stamping ingestion time.
	b.WriteString(kv("json_date_key", "_timestamp"))
	b.WriteString(kv("json_date_format", "iso8601"))
	return b.String()
}

// renderForward emits the forward output, shipping to another Fluent Bit or Fluentd.
func renderForward(name string, d *vestav1alpha1.ForwardDrain) string {
	var b strings.Builder
	b.WriteString(kv("Name", "forward"))
	b.WriteString(kv("Alias", name))
	b.WriteString(kv("Host", d.Host))
	b.WriteString(kv("Port", portOrDefault(d.Port, 24224)))

	if d.SharedKey != nil {
		b.WriteString(kv("Shared_Key", "${"+secretEnvVar(name, "SHARED_KEY")+"}"))
		// The handshake needs both sides to agree on a hostname. The pod name would change
		// on every restart, so a stable default is used unless one is given.
		b.WriteString(kv("Self_Hostname", orDefault(d.SelfHostname, "vesta-logs")))
	}
	if boolOr(d.TLS, false) {
		b.WriteString(kv("tls", "On"))
		b.WriteString(kv("tls.verify", onOff(d.TLSVerify, true)))
	}
	if boolOr(d.TimeAsInteger, false) {
		b.WriteString(kv("Time_as_Integer", "On"))
	}
	return b.String()
}
