//go:build !ignore_autogenerated

package v1alpha1

import (
	autoscalingv2 "k8s.io/api/autoscaling/v2"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

var (
	_ = corev1.LocalObjectReference{}
	_ = metav1.Condition{}
	_ = autoscalingv2.HorizontalPodAutoscalerBehavior{}
)

// --- VestaApp ---

func (in *VestaApp) DeepCopyInto(out *VestaApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *VestaApp) DeepCopy() *VestaApp {
	if in == nil {
		return nil
	}
	out := new(VestaApp)
	in.DeepCopyInto(out)
	return out
}

func (in *VestaApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- VestaAppList ---

func (in *VestaAppList) DeepCopyInto(out *VestaAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VestaApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VestaAppList) DeepCopy() *VestaAppList {
	if in == nil {
		return nil
	}
	out := new(VestaAppList)
	in.DeepCopyInto(out)
	return out
}

func (in *VestaAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- VestaAppSpec ---

func (in *VestaAppSpec) DeepCopyInto(out *VestaAppSpec) {
	*out = *in
	if in.Environments != nil {
		in, out := &in.Environments, &out.Environments
		*out = make([]AppEnvironmentConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(GitSource)
		**out = **in
	}
	if in.Build != nil {
		in, out := &in.Build, &out.Build
		*out = new(BuildConfig)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImageConfig)
		(*in).DeepCopyInto(*out)
	}
	in.Runtime.DeepCopyInto(&out.Runtime)
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(IngressConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Cronjobs != nil {
		in, out := &in.Cronjobs, &out.Cronjobs
		*out = make([]CronjobConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Addons != nil {
		in, out := &in.Addons, &out.Addons
		*out = make([]AddonConfig, len(*in))
		copy(*out, *in)
	}
	if in.Sleep != nil {
		in, out := &in.Sleep, &out.Sleep
		*out = new(SleepConfig)
		**out = **in
	}
	if in.CustomConfig != nil {
		in, out := &in.CustomConfig, &out.CustomConfig
		*out = new(CustomConfig)
		(*in).DeepCopyInto(*out)
	}
}

func (in *VestaAppSpec) DeepCopy() *VestaAppSpec {
	if in == nil {
		return nil
	}
	out := new(VestaAppSpec)
	in.DeepCopyInto(out)
	return out
}

// --- AppEnvironmentConfig ---

func (in *AppEnvironmentConfig) DeepCopyInto(out *AppEnvironmentConfig) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Autoscale != nil {
		in, out := &in.Autoscale, &out.Autoscale
		*out = new(AutoscaleConfig)
		(*in).DeepCopyInto(*out)
	}
}

func (in *AppEnvironmentConfig) DeepCopy() *AppEnvironmentConfig {
	if in == nil {
		return nil
	}
	out := new(AppEnvironmentConfig)
	in.DeepCopyInto(out)
	return out
}

// --- GitSource ---

func (in *GitSource) DeepCopyInto(out *GitSource) {
	*out = *in
}

func (in *GitSource) DeepCopy() *GitSource {
	if in == nil {
		return nil
	}
	out := new(GitSource)
	in.DeepCopyInto(out)
	return out
}

// --- BuildConfig ---

func (in *BuildConfig) DeepCopyInto(out *BuildConfig) {
	*out = *in
}

func (in *BuildConfig) DeepCopy() *BuildConfig {
	if in == nil {
		return nil
	}
	out := new(BuildConfig)
	in.DeepCopyInto(out)
	return out
}

// --- ImageConfig ---

func (in *ImageConfig) DeepCopyInto(out *ImageConfig) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

func (in *ImageConfig) DeepCopy() *ImageConfig {
	if in == nil {
		return nil
	}
	out := new(ImageConfig)
	in.DeepCopyInto(out)
	return out
}

// --- RuntimeConfig ---

func (in *RuntimeConfig) DeepCopyInto(out *RuntimeConfig) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]SecretBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *RuntimeConfig) DeepCopy() *RuntimeConfig {
	if in == nil {
		return nil
	}
	out := new(RuntimeConfig)
	in.DeepCopyInto(out)
	return out
}

// --- SecretBinding ---

func (in *SecretBinding) DeepCopyInto(out *SecretBinding) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretRefBinding)
		**out = **in
	}
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(SecretKeyRefBinding)
		**out = **in
	}
	if in.SecretMount != nil {
		in, out := &in.SecretMount, &out.SecretMount
		*out = new(SecretMountBinding)
		**out = **in
	}
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]SecretKeyMapping, len(*in))
		copy(*out, *in)
	}
}

func (in *SecretBinding) DeepCopy() *SecretBinding {
	if in == nil {
		return nil
	}
	out := new(SecretBinding)
	in.DeepCopyInto(out)
	return out
}

// --- SecretRefBinding ---

func (in *SecretRefBinding) DeepCopyInto(out *SecretRefBinding) {
	*out = *in
}

func (in *SecretRefBinding) DeepCopy() *SecretRefBinding {
	if in == nil {
		return nil
	}
	out := new(SecretRefBinding)
	in.DeepCopyInto(out)
	return out
}

// --- SecretKeyRefBinding ---

func (in *SecretKeyRefBinding) DeepCopyInto(out *SecretKeyRefBinding) {
	*out = *in
}

func (in *SecretKeyRefBinding) DeepCopy() *SecretKeyRefBinding {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRefBinding)
	in.DeepCopyInto(out)
	return out
}

// --- SecretMountBinding ---

func (in *SecretMountBinding) DeepCopyInto(out *SecretMountBinding) {
	*out = *in
}

func (in *SecretMountBinding) DeepCopy() *SecretMountBinding {
	if in == nil {
		return nil
	}
	out := new(SecretMountBinding)
	in.DeepCopyInto(out)
	return out
}

// --- SecretKeyMapping ---

func (in *SecretKeyMapping) DeepCopyInto(out *SecretKeyMapping) {
	*out = *in
}

func (in *SecretKeyMapping) DeepCopy() *SecretKeyMapping {
	if in == nil {
		return nil
	}
	out := new(SecretKeyMapping)
	in.DeepCopyInto(out)
	return out
}

// --- VolumeMount ---

func (in *VolumeMount) DeepCopyInto(out *VolumeMount) {
	*out = *in
	if in.PersistentVolumeClaim != nil {
		in, out := &in.PersistentVolumeClaim, &out.PersistentVolumeClaim
		*out = new(PVCRef)
		**out = **in
	}
}

func (in *VolumeMount) DeepCopy() *VolumeMount {
	if in == nil {
		return nil
	}
	out := new(VolumeMount)
	in.DeepCopyInto(out)
	return out
}

// --- PVCRef ---

func (in *PVCRef) DeepCopyInto(out *PVCRef) {
	*out = *in
}

func (in *PVCRef) DeepCopy() *PVCRef {
	if in == nil {
		return nil
	}
	out := new(PVCRef)
	in.DeepCopyInto(out)
	return out
}

// --- ScalingConfig ---

func (in *ScalingConfig) DeepCopyInto(out *ScalingConfig) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Autoscale != nil {
		in, out := &in.Autoscale, &out.Autoscale
		*out = new(AutoscaleConfig)
		(*in).DeepCopyInto(*out)
	}
}

func (in *ScalingConfig) DeepCopy() *ScalingConfig {
	if in == nil {
		return nil
	}
	out := new(ScalingConfig)
	in.DeepCopyInto(out)
	return out
}

// --- AutoscaleConfig ---

func (in *AutoscaleConfig) DeepCopyInto(out *AutoscaleConfig) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]MetricSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Behavior != nil {
		in, out := &in.Behavior, &out.Behavior
		*out = new(autoscalingv2.HorizontalPodAutoscalerBehavior)
		(*in).DeepCopyInto(*out)
	}
}

func (in *AutoscaleConfig) DeepCopy() *AutoscaleConfig {
	if in == nil {
		return nil
	}
	out := new(AutoscaleConfig)
	in.DeepCopyInto(out)
	return out
}

// --- MetricSpec ---

func (in *MetricSpec) DeepCopyInto(out *MetricSpec) {
	*out = *in
	if in.TargetAverageUtilization != nil {
		in, out := &in.TargetAverageUtilization, &out.TargetAverageUtilization
		*out = new(int32)
		**out = **in
	}
}

func (in *MetricSpec) DeepCopy() *MetricSpec {
	if in == nil {
		return nil
	}
	out := new(MetricSpec)
	in.DeepCopyInto(out)
	return out
}

// --- ResourceConfig ---

func (in *ResourceConfig) DeepCopyInto(out *ResourceConfig) {
	*out = *in
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = in.DeepCopy()
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = in.DeepCopy()
	}
}

func (in *ResourceConfig) DeepCopy() *ResourceConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// --- IngressConfig ---

func (in *IngressConfig) DeepCopyInto(out *IngressConfig) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
}

func (in *IngressConfig) DeepCopy() *IngressConfig {
	if in == nil {
		return nil
	}
	out := new(IngressConfig)
	in.DeepCopyInto(out)
	return out
}

// --- CronjobConfig ---

func (in *CronjobConfig) DeepCopyInto(out *CronjobConfig) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceConfig)
		(*in).DeepCopyInto(*out)
	}
}

func (in *CronjobConfig) DeepCopy() *CronjobConfig {
	if in == nil {
		return nil
	}
	out := new(CronjobConfig)
	in.DeepCopyInto(out)
	return out
}

// --- AddonConfig ---

func (in *AddonConfig) DeepCopyInto(out *AddonConfig) {
	*out = *in
}

func (in *AddonConfig) DeepCopy() *AddonConfig {
	if in == nil {
		return nil
	}
	out := new(AddonConfig)
	in.DeepCopyInto(out)
	return out
}

// --- SleepConfig ---

func (in *SleepConfig) DeepCopyInto(out *SleepConfig) {
	*out = *in
}

func (in *SleepConfig) DeepCopy() *SleepConfig {
	if in == nil {
		return nil
	}
	out := new(SleepConfig)
	in.DeepCopyInto(out)
	return out
}

// --- CustomConfig ---

func (in *CustomConfig) DeepCopyInto(out *CustomConfig) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
	if in.PodSpec != nil {
		in, out := &in.PodSpec, &out.PodSpec
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerSpec != nil {
		in, out := &in.ContainerSpec, &out.ContainerSpec
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraResources != nil {
		in, out := &in.ExtraResources, &out.ExtraResources
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *CustomConfig) DeepCopy() *CustomConfig {
	if in == nil {
		return nil
	}
	out := new(CustomConfig)
	in.DeepCopyInto(out)
	return out
}

// --- VestaAppStatus ---

func (in *VestaAppStatus) DeepCopyInto(out *VestaAppStatus) {
	*out = *in
	if in.DeploymentHistory != nil {
		in, out := &in.DeploymentHistory, &out.DeploymentHistory
		*out = make([]DeploymentRecord, len(*in))
		copy(*out, *in)
	}
	if in.Scaling != nil {
		in, out := &in.Scaling, &out.Scaling
		*out = new(ScalingStatus)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VestaAppStatus) DeepCopy() *VestaAppStatus {
	if in == nil {
		return nil
	}
	out := new(VestaAppStatus)
	in.DeepCopyInto(out)
	return out
}

// --- DeploymentRecord ---

func (in *DeploymentRecord) DeepCopyInto(out *DeploymentRecord) {
	*out = *in
}

func (in *DeploymentRecord) DeepCopy() *DeploymentRecord {
	if in == nil {
		return nil
	}
	out := new(DeploymentRecord)
	in.DeepCopyInto(out)
	return out
}

// --- ScalingStatus ---

func (in *ScalingStatus) DeepCopyInto(out *ScalingStatus) {
	*out = *in
}

func (in *ScalingStatus) DeepCopy() *ScalingStatus {
	if in == nil {
		return nil
	}
	out := new(ScalingStatus)
	in.DeepCopyInto(out)
	return out
}

// --- VestaProject ---

func (in *VestaProject) DeepCopyInto(out *VestaProject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *VestaProject) DeepCopy() *VestaProject {
	if in == nil {
		return nil
	}
	out := new(VestaProject)
	in.DeepCopyInto(out)
	return out
}

func (in *VestaProject) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- VestaProjectList ---

func (in *VestaProjectList) DeepCopyInto(out *VestaProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VestaProject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VestaProjectList) DeepCopy() *VestaProjectList {
	if in == nil {
		return nil
	}
	out := new(VestaProjectList)
	in.DeepCopyInto(out)
	return out
}

func (in *VestaProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- VestaProjectSpec ---

func (in *VestaProjectSpec) DeepCopyInto(out *VestaProjectSpec) {
	*out = *in
	if in.Environments != nil {
		in, out := &in.Environments, &out.Environments
		*out = make([]ProjectEnvironment, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
	if in.DefaultGit != nil {
		in, out := &in.DefaultGit, &out.DefaultGit
		*out = new(GitSource)
		**out = **in
	}
	if in.DefaultBuild != nil {
		in, out := &in.DefaultBuild, &out.DefaultBuild
		*out = new(BuildConfig)
		**out = **in
	}
	if in.DefaultImage != nil {
		in, out := &in.DefaultImage, &out.DefaultImage
		*out = new(ImageConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = new(NotificationConfig)
		(*in).DeepCopyInto(*out)
	}
}

func (in *VestaProjectSpec) DeepCopy() *VestaProjectSpec {
	if in == nil {
		return nil
	}
	out := new(VestaProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// --- NotificationConfig ---

func (in *NotificationConfig) DeepCopyInto(out *NotificationConfig) {
	*out = *in
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(SlackNotification)
		(*in).DeepCopyInto(*out)
	}
	if in.Discord != nil {
		in, out := &in.Discord, &out.Discord
		*out = new(DiscordNotification)
		(*in).DeepCopyInto(*out)
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(WebhookNotification)
		(*in).DeepCopyInto(*out)
	}
}

func (in *NotificationConfig) DeepCopy() *NotificationConfig {
	if in == nil {
		return nil
	}
	out := new(NotificationConfig)
	in.DeepCopyInto(out)
	return out
}

// --- SlackNotification ---

func (in *SlackNotification) DeepCopyInto(out *SlackNotification) {
	*out = *in
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *SlackNotification) DeepCopy() *SlackNotification {
	if in == nil {
		return nil
	}
	out := new(SlackNotification)
	in.DeepCopyInto(out)
	return out
}

// --- DiscordNotification ---

func (in *DiscordNotification) DeepCopyInto(out *DiscordNotification) {
	*out = *in
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *DiscordNotification) DeepCopy() *DiscordNotification {
	if in == nil {
		return nil
	}
	out := new(DiscordNotification)
	in.DeepCopyInto(out)
	return out
}

// --- WebhookNotification ---

func (in *WebhookNotification) DeepCopyInto(out *WebhookNotification) {
	*out = *in
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *WebhookNotification) DeepCopy() *WebhookNotification {
	if in == nil {
		return nil
	}
	out := new(WebhookNotification)
	in.DeepCopyInto(out)
	return out
}

// --- VestaProjectStatus ---

func (in *VestaProjectStatus) DeepCopyInto(out *VestaProjectStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VestaProjectStatus) DeepCopy() *VestaProjectStatus {
	if in == nil {
		return nil
	}
	out := new(VestaProjectStatus)
	in.DeepCopyInto(out)
	return out
}

// --- VestaEnvironment ---

func (in *VestaEnvironment) DeepCopyInto(out *VestaEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *VestaEnvironment) DeepCopy() *VestaEnvironment {
	if in == nil {
		return nil
	}
	out := new(VestaEnvironment)
	in.DeepCopyInto(out)
	return out
}

func (in *VestaEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- VestaEnvironmentList ---

func (in *VestaEnvironmentList) DeepCopyInto(out *VestaEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VestaEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VestaEnvironmentList) DeepCopy() *VestaEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(VestaEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

func (in *VestaEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- VestaEnvironmentSpec ---

func (in *VestaEnvironmentSpec) DeepCopyInto(out *VestaEnvironmentSpec) {
	*out = *in
}

func (in *VestaEnvironmentSpec) DeepCopy() *VestaEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(VestaEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// --- VestaEnvironmentStatus ---

func (in *VestaEnvironmentStatus) DeepCopyInto(out *VestaEnvironmentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VestaEnvironmentStatus) DeepCopy() *VestaEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(VestaEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// --- VestaConfig ---

func (in *VestaConfig) DeepCopyInto(out *VestaConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *VestaConfig) DeepCopy() *VestaConfig {
	if in == nil {
		return nil
	}
	out := new(VestaConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *VestaConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- VestaConfigList ---

func (in *VestaConfigList) DeepCopyInto(out *VestaConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VestaConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VestaConfigList) DeepCopy() *VestaConfigList {
	if in == nil {
		return nil
	}
	out := new(VestaConfigList)
	in.DeepCopyInto(out)
	return out
}

func (in *VestaConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- VestaConfigSpec ---

func (in *VestaConfigSpec) DeepCopyInto(out *VestaConfigSpec) {
	*out = *in
	if in.Registry != nil {
		in, out := &in.Registry, &out.Registry
		*out = new(RegistryConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PodSizeList != nil {
		in, out := &in.PodSizeList, &out.PodSizeList
		*out = make([]PodSizePreset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AutoscaleDefaults != nil {
		in, out := &in.AutoscaleDefaults, &out.AutoscaleDefaults
		*out = new(AutoscaleDefaults)
		(*in).DeepCopyInto(*out)
	}
	if in.Buildpacks != nil {
		in, out := &in.Buildpacks, &out.Buildpacks
		*out = make([]BuildpackConfig, len(*in))
		copy(*out, *in)
	}
	if in.ExternalSecrets != nil {
		in, out := &in.ExternalSecrets, &out.ExternalSecrets
		*out = new(ExternalSecretsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(AuthConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Templates != nil {
		in, out := &in.Templates, &out.Templates
		*out = new(TemplatesConfig)
		**out = **in
	}
}

func (in *VestaConfigSpec) DeepCopy() *VestaConfigSpec {
	if in == nil {
		return nil
	}
	out := new(VestaConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// --- RegistryConfig ---

func (in *RegistryConfig) DeepCopyInto(out *RegistryConfig) {
	*out = *in
	in.Build.DeepCopyInto(&out.Build)
	if in.GlobalImagePullSecrets != nil {
		in, out := &in.GlobalImagePullSecrets, &out.GlobalImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

func (in *RegistryConfig) DeepCopy() *RegistryConfig {
	if in == nil {
		return nil
	}
	out := new(RegistryConfig)
	in.DeepCopyInto(out)
	return out
}

// --- BuildRegistryConfig ---

func (in *BuildRegistryConfig) DeepCopyInto(out *BuildRegistryConfig) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(CredentialRef)
		**out = **in
	}
}

func (in *BuildRegistryConfig) DeepCopy() *BuildRegistryConfig {
	if in == nil {
		return nil
	}
	out := new(BuildRegistryConfig)
	in.DeepCopyInto(out)
	return out
}

// --- CredentialRef ---

func (in *CredentialRef) DeepCopyInto(out *CredentialRef) {
	*out = *in
}

func (in *CredentialRef) DeepCopy() *CredentialRef {
	if in == nil {
		return nil
	}
	out := new(CredentialRef)
	in.DeepCopyInto(out)
	return out
}

// --- PodSizePreset ---

func (in *PodSizePreset) DeepCopyInto(out *PodSizePreset) {
	*out = *in
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = in.DeepCopy()
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = in.DeepCopy()
	}
}

func (in *PodSizePreset) DeepCopy() *PodSizePreset {
	if in == nil {
		return nil
	}
	out := new(PodSizePreset)
	in.DeepCopyInto(out)
	return out
}

// --- AutoscaleDefaults ---

func (in *AutoscaleDefaults) DeepCopyInto(out *AutoscaleDefaults) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
	if in.TargetCPU != nil {
		in, out := &in.TargetCPU, &out.TargetCPU
		*out = new(int32)
		**out = **in
	}
	if in.TargetMemory != nil {
		in, out := &in.TargetMemory, &out.TargetMemory
		*out = new(int32)
		**out = **in
	}
}

func (in *AutoscaleDefaults) DeepCopy() *AutoscaleDefaults {
	if in == nil {
		return nil
	}
	out := new(AutoscaleDefaults)
	in.DeepCopyInto(out)
	return out
}

// --- BuildpackConfig ---

func (in *BuildpackConfig) DeepCopyInto(out *BuildpackConfig) {
	*out = *in
}

func (in *BuildpackConfig) DeepCopy() *BuildpackConfig {
	if in == nil {
		return nil
	}
	out := new(BuildpackConfig)
	in.DeepCopyInto(out)
	return out
}

// --- ExternalSecretsConfig ---

func (in *ExternalSecretsConfig) DeepCopyInto(out *ExternalSecretsConfig) {
	*out = *in
	if in.Vault != nil {
		in, out := &in.Vault, &out.Vault
		*out = new(VaultConfig)
		(*in).DeepCopyInto(*out)
	}
}

func (in *ExternalSecretsConfig) DeepCopy() *ExternalSecretsConfig {
	if in == nil {
		return nil
	}
	out := new(ExternalSecretsConfig)
	in.DeepCopyInto(out)
	return out
}

// --- VaultConfig ---

func (in *VaultConfig) DeepCopyInto(out *VaultConfig) {
	*out = *in
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(VaultAuth)
		**out = **in
	}
}

func (in *VaultConfig) DeepCopy() *VaultConfig {
	if in == nil {
		return nil
	}
	out := new(VaultConfig)
	in.DeepCopyInto(out)
	return out
}

// --- VaultAuth ---

func (in *VaultAuth) DeepCopyInto(out *VaultAuth) {
	*out = *in
}

func (in *VaultAuth) DeepCopy() *VaultAuth {
	if in == nil {
		return nil
	}
	out := new(VaultAuth)
	in.DeepCopyInto(out)
	return out
}

// --- AuthConfig ---

func (in *AuthConfig) DeepCopyInto(out *AuthConfig) {
	*out = *in
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = new(LocalAuthConfig)
		**out = **in
	}
	if in.OAuth2 != nil {
		in, out := &in.OAuth2, &out.OAuth2
		*out = new(OAuth2Config)
		(*in).DeepCopyInto(*out)
	}
	if in.APITokens != nil {
		in, out := &in.APITokens, &out.APITokens
		*out = new(APITokenConfig)
		**out = **in
	}
}

func (in *AuthConfig) DeepCopy() *AuthConfig {
	if in == nil {
		return nil
	}
	out := new(AuthConfig)
	in.DeepCopyInto(out)
	return out
}

// --- LocalAuthConfig ---

func (in *LocalAuthConfig) DeepCopyInto(out *LocalAuthConfig) {
	*out = *in
}

func (in *LocalAuthConfig) DeepCopy() *LocalAuthConfig {
	if in == nil {
		return nil
	}
	out := new(LocalAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// --- OAuth2Config ---

func (in *OAuth2Config) DeepCopyInto(out *OAuth2Config) {
	*out = *in
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]OAuth2Provider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *OAuth2Config) DeepCopy() *OAuth2Config {
	if in == nil {
		return nil
	}
	out := new(OAuth2Config)
	in.DeepCopyInto(out)
	return out
}

// --- OAuth2Provider ---

func (in *OAuth2Provider) DeepCopyInto(out *OAuth2Provider) {
	*out = *in
	if in.AllowedOrgs != nil {
		in, out := &in.AllowedOrgs, &out.AllowedOrgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *OAuth2Provider) DeepCopy() *OAuth2Provider {
	if in == nil {
		return nil
	}
	out := new(OAuth2Provider)
	in.DeepCopyInto(out)
	return out
}

// --- APITokenConfig ---

func (in *APITokenConfig) DeepCopyInto(out *APITokenConfig) {
	*out = *in
}

func (in *APITokenConfig) DeepCopy() *APITokenConfig {
	if in == nil {
		return nil
	}
	out := new(APITokenConfig)
	in.DeepCopyInto(out)
	return out
}

// --- TemplatesConfig ---

func (in *TemplatesConfig) DeepCopyInto(out *TemplatesConfig) {
	*out = *in
}

func (in *TemplatesConfig) DeepCopy() *TemplatesConfig {
	if in == nil {
		return nil
	}
	out := new(TemplatesConfig)
	in.DeepCopyInto(out)
	return out
}

// --- VestaSecret ---

func (in *VestaSecret) DeepCopyInto(out *VestaSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

func (in *VestaSecret) DeepCopy() *VestaSecret {
	if in == nil {
		return nil
	}
	out := new(VestaSecret)
	in.DeepCopyInto(out)
	return out
}

func (in *VestaSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- VestaSecretList ---

func (in *VestaSecretList) DeepCopyInto(out *VestaSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VestaSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VestaSecretList) DeepCopy() *VestaSecretList {
	if in == nil {
		return nil
	}
	out := new(VestaSecretList)
	in.DeepCopyInto(out)
	return out
}

func (in *VestaSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- VestaSecretSpec ---

func (in *VestaSecretSpec) DeepCopyInto(out *VestaSecretSpec) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
	if in.DockerConfig != nil {
		in, out := &in.DockerConfig, &out.DockerConfig
		*out = new(DockerSecretConfig)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSSecretConfig)
		**out = **in
	}
	if in.ExternalSecret != nil {
		in, out := &in.ExternalSecret, &out.ExternalSecret
		*out = new(ExternalSecretRef)
		(*in).DeepCopyInto(*out)
	}
}

func (in *VestaSecretSpec) DeepCopy() *VestaSecretSpec {
	if in == nil {
		return nil
	}
	out := new(VestaSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// --- VestaSecretStatus ---

func (in *VestaSecretStatus) DeepCopyInto(out *VestaSecretStatus) {
	*out = *in
}

func (in *VestaSecretStatus) DeepCopy() *VestaSecretStatus {
	if in == nil {
		return nil
	}
	out := new(VestaSecretStatus)
	in.DeepCopyInto(out)
	return out
}

// --- DockerSecretConfig ---

func (in *DockerSecretConfig) DeepCopyInto(out *DockerSecretConfig) {
	*out = *in
}

func (in *DockerSecretConfig) DeepCopy() *DockerSecretConfig {
	if in == nil {
		return nil
	}
	out := new(DockerSecretConfig)
	in.DeepCopyInto(out)
	return out
}

// --- TLSSecretConfig ---

func (in *TLSSecretConfig) DeepCopyInto(out *TLSSecretConfig) {
	*out = *in
}

func (in *TLSSecretConfig) DeepCopy() *TLSSecretConfig {
	if in == nil {
		return nil
	}
	out := new(TLSSecretConfig)
	in.DeepCopyInto(out)
	return out
}

// --- ExternalSecretRef ---

func (in *ExternalSecretRef) DeepCopyInto(out *ExternalSecretRef) {
	*out = *in
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]ExternalKeyMapping, len(*in))
		copy(*out, *in)
	}
}

func (in *ExternalSecretRef) DeepCopy() *ExternalSecretRef {
	if in == nil {
		return nil
	}
	out := new(ExternalSecretRef)
	in.DeepCopyInto(out)
	return out
}

// --- ExternalKeyMapping ---

func (in *ExternalKeyMapping) DeepCopyInto(out *ExternalKeyMapping) {
	*out = *in
}

func (in *ExternalKeyMapping) DeepCopy() *ExternalKeyMapping {
	if in == nil {
		return nil
	}
	out := new(ExternalKeyMapping)
	in.DeepCopyInto(out)
	return out
}
